// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKarZldyJK4vGs9o3eDWHQtlm5aBXtsrc',
    appId: '1:517279159932:web:ebeebeb8a4f6106ddd1bf9',
    messagingSenderId: '517279159932',
    projectId: 'loja-virtual-mentoria',
    authDomain: 'loja-virtual-mentoria.firebaseapp.com',
    storageBucket: 'loja-virtual-mentoria.appspot.com',
    measurementId: 'G-E92KQ983RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0-sBLWrWXHTppXzWfC_mQtone-eLOn8',
    appId: '1:517279159932:android:ffd3f281b4b64ccedd1bf9',
    messagingSenderId: '517279159932',
    projectId: 'loja-virtual-mentoria',
    storageBucket: 'loja-virtual-mentoria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUXMSSP1scEOgrKw5BMH5BfQVfEMy6rBQ',
    appId: '1:517279159932:ios:8a43fe1f139a0348dd1bf9',
    messagingSenderId: '517279159932',
    projectId: 'loja-virtual-mentoria',
    storageBucket: 'loja-virtual-mentoria.appspot.com',
    iosClientId: '517279159932-s23ev3t6q32ptvoi9ngtk5fbukpigo6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojaVirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUXMSSP1scEOgrKw5BMH5BfQVfEMy6rBQ',
    appId: '1:517279159932:ios:3d6f320d1b798457dd1bf9',
    messagingSenderId: '517279159932',
    projectId: 'loja-virtual-mentoria',
    storageBucket: 'loja-virtual-mentoria.appspot.com',
    iosClientId: '517279159932-n1bctsmtaoq2po02oupemebmnlib61i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojaVirtual.RunnerTests',
  );
}
